#!/usr/bin/env bash
# Render coldstart/*.py + scripts/coldstart-run.sh into a ConfigMap manifest.
#
# The probe ships as a ConfigMap so no image rebuild and no vLLM fork are
# needed: the pod mounts it read-only and puts it on PYTHONPATH, and Python's
# site machinery imports sitecustomize.py from there during interpreter startup.
#
#   scripts/build-probe-configmap.sh [-n namespace] [-o out.yaml] [--name cm]
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NS="${NAMESPACE:-}"
NAME="${CM_NAME:-coldstart-probe}"
OUT="$REPO/manifests/generated/probe-configmap.yaml"

while [[ $# -gt 0 ]]; do
  case "$1" in
    -n|--namespace) NS="$2"; shift 2 ;;
    -o|--out) OUT="$2"; shift 2 ;;
    --name) NAME="$2"; shift 2 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

mkdir -p "$(dirname "$OUT")"
{
  echo "# Generated by scripts/build-probe-configmap.sh -- do not edit."
  echo "# Source of truth: coldstart/*.py, scripts/coldstart-run.sh"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: $NAME"
  [[ -n "$NS" ]] && echo "  namespace: $NS"
  echo "  labels:"
  echo "    app.kubernetes.io/part-of: llm-d-cold-start"
  echo "data:"
  for f in "$REPO"/coldstart/*.py "$REPO"/scripts/coldstart-run.sh; do
    echo "  $(basename "$f"): |"
    # 4-space indent under a block scalar; tabs would be invalid YAML indent.
    sed -e 's/\r$//' -e 's/^/    /' -e 's/[[:space:]]*$//' "$f"
  done
} > "$OUT"

size=$(wc -c < "$OUT")
echo "wrote $OUT ($size bytes)"
# etcd refuses objects over ~1 MiB; the probe is far smaller, but a stray
# addition (a wheel, a model file) would silently break every deploy.
if [[ "$size" -gt 900000 ]]; then
  echo "!! ConfigMap is ${size} bytes -- approaching the 1 MiB object limit" >&2
  exit 1
fi
